// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class Corporate_SPResult
    {
        public int? No_Of_visit { get; set; }
        public string Fullname { get; set; }
        public string BusinessName { get; set; }
        public string CorporateName { get; set; }
        public string Privilegename { get; set; }
        public string Country { get; set; }
        public string BusinessTypeName { get; set; }
        public int Id { get; set; }
        public string VendorName { get; set; }
    }
}
