// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class SP_BusinessHotelListResult
    {
        public string Description { get; set; }
        public string FeatureImg { get; set; }
        public string Status { get; set; }
        public string HotelName { get; set; }
        public int Id { get; set; }
        public string Location { get; set; }
        public string BusinessID { get; set; }
    }
}
