// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class SP_GetPFByUserAndBTypeResult
    {
        public string Username { get; set; }
        public string EmployeeID { get; set; }
        public string Title { get; set; }
        public DateTime? Validity { get; set; }
        public string VendorID { get; set; }
        public string BusinessTypeName { get; set; }
        public string PrivilegeID { get; set; }
        public string PrivilegeImg { get; set; }
        public string VendorLogo { get; set; }
        public string Description { get; set; }
        public string Mechanics { get; set; }
        public string TMC { get; set; }
        public int? Id { get; set; }
    }
}
