// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class SP_GetAllPrivilegeCardbyUserResult
    {
        public string Username { get; set; }
        public string EmployeeID { get; set; }
        public string Title { get; set; }
        public DateTime? Validity { get; set; }
        public string PrivilegeImg { get; set; }
        public string FileUrl { get; set; }
        public string PrivilegeID { get; set; }
        public string VendorLogo { get; set; }
    }
}
