// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class SP_GetOfferingFilteredbyVIDResult
    {
        public string BusinessTypeName { get; set; }
        public string VendorName { get; set; }
        public string PromoReleaseText { get; set; }
        public string OfferingName { get; set; }
        public string MembershipName { get; set; }
        public string VendorID { get; set; }
        public string ImgUrl { get; set; }
        public int Id { get; set; }
        public string OfferingID { get; set; }
        public string Status { get; set; }
    }
}
