// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class SP_PrivilegeCardListResult
    {
        public string Title { get; set; }
        public int Id { get; set; }
        public string ImgUrl { get; set; }
        public string VendorName { get; set; }
        public DateTime? Validity { get; set; }
        public string FeatureImg { get; set; }
        public string VendorID { get; set; }
        public string Status { get; set; }
    }
}
