// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblAudittrailModel
{
    public int Id { get; set; }

    public string Actions { get; set; }

    public string Module { get; set; }

    public DateTime DateCreated { get; set; }

    public int? UserId { get; set; }

    public int? Status { get; set; }

    public string EmployeeId { get; set; }

    public string ActionId { get; set; }

    public string Business { get; set; }
}