// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblBusinessModel
{
    public int Id { get; set; }

    public string BusinessName { get; set; }

    public int? TypeId { get; set; }

    public int? LocationId { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public string Cno { get; set; }

    public string Email { get; set; }

    public string Url { get; set; }

    public string Services { get; set; }

    public string FeatureImg { get; set; }

    public string Gallery { get; set; }

    public DateTime DateCreated { get; set; }

    public int? Active { get; set; }

    public string BusinessId { get; set; }

    public string FilePath { get; set; }

    public string Map { get; set; }
}