// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblCorporateModel
{
    public int Id { get; set; }

    public string CorporateName { get; set; }

    public string Address { get; set; }

    public string Cno { get; set; }

    public string EmailAddress { get; set; }

    public DateTime DateCreated { get; set; }

    public int? Status { get; set; }

    public string CompanyId { get; set; }

    public int? MembershipId { get; set; }

    public int? Count { get; set; }

    public int? VipCount { get; set; }

    public DateTime? DateUsed { get; set; }

    public DateTime? DateEnded { get; set; }
}