// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblDeletedUserModel
{
    public int Id { get; set; }

    public string UserEmail { get; set; }

    public string Reason { get; set; }

    public DateTime DateDeleted { get; set; }
}