// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblMembershipPrivilegeModel
{
    public int Id { get; set; }

    public int? PrivilegeId { get; set; }

    public int? MembershipId { get; set; }

    public int? Count { get; set; }

    public int? VipCount { get; set; }
}