// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblQrCodeLogsModel
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public string Longtitude { get; set; }

    public string Latitude { get; set; }

    public string Ipaddres { get; set; }

    public string Region { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string AreaCode { get; set; }

    public string ZipCode { get; set; }

    public string Isocode { get; set; }

    public string MetroCode { get; set; }

    public string TimeZone { get; set; }

    public DateTime DateCreated { get; set; }

    public string PostalCode { get; set; }
}