// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblSupportModel
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public string Message { get; set; }

    public DateTime DateCreated { get; set; }

    public int? Status { get; set; }
}