// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class Test
{
    public int Test1 { get; set; }

    public string Testid { get; set; }

    public string Testname { get; set; }

    public string Qweqwe { get; set; }
}