// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using API.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace API.Models
{
    public partial interface IAOPCDBContextProcedures
    {
        Task<List<Corporate_SPResult>> Corporate_SPAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Get_PrivilegeisVIPResult>> Get_PrivilegeisVIPAsync(string EmployeeID, string BusinessTypeName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_BusinessHotelListResult>> SP_BusinessHotelListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_DiscoverFilterbyBtypeAndBIDResult>> SP_DiscoverFilterbyBtypeAndBIDAsync(string BusinessTypeName, string BusinessID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetAllPrivilegeCardbyUserResult>> SP_GetAllPrivilegeCardbyUserAsync(string EmployeeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetBFByBIDResult>> SP_GetBFByBIDAsync(string BusinessID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetOfferingFilteredbyVIDResult>> SP_GetOfferingFilteredbyVIDAsync(string VendorID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetOfferingFilterListResult>> SP_GetOfferingFilterListAsync(string BusinessTypeName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetPFByUserAndBTypeResult>> SP_GetPFByUserAndBTypeAsync(string BusinessTypeName, string EmployeeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetPrivilegeByPIDResult>> SP_GetPrivilegeByPIDAsync(string PrivilegeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetPrivilegeFbyUandBtypeResult>> SP_GetPrivilegeFbyUandBtypeAsync(int? BusinessTypeID, string EmployeeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetVendorOfferingsResult>> SP_GetVendorOfferingsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_OfferingListResult>> SP_OfferingListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_PrivilegeCardListResult>> SP_PrivilegeCardListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UserInfoResult>> SP_UserInfoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_UserInfoListResult>> SP_UserInfoListAsync(string jwToken, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
