// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class SP_UserInfoResult
    {
        public string Username { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string EmployeeID { get; set; }
        public string Position { get; set; }
        public string CorporateName { get; set; }
        public string UserType { get; set; }
        public string Fullname { get; set; }
        public int Id { get; set; }
        public DateTime DateCreated { get; set; }
        public int PositionID { get; set; }
        public int CorporateID { get; set; }
        public string status { get; set; }
        public int? AllowEmailNotif { get; set; }
    }
}
