// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models
{
    public partial class SP_UserInfoListResult
    {
        public string Username { get; set; }
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string EmployeeID { get; set; }
        public int? isVIP { get; set; }
        public string CorporateName { get; set; }
        public string PositionName { get; set; }
        public string UserType { get; set; }
        public string Status { get; set; }
        public string Cno { get; set; }
        public string Address { get; set; }
        public string MembershipName { get; set; }
        public string companyAddress { get; set; }
        public string ProfileImgPath { get; set; }
        public string MembershipNumber { get; set; }
        public DateTime MemValidity { get; set; }
        public string CorpCno { get; set; }
        public int? AllowEmailNotif { get; set; }
        public string MembershipCard { get; set; }
        public string VIPCard { get; set; }
        public string QRFrame { get; set; }
        public string VIPBadge { get; set; }
    }
}
