// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblBusinessTypeModel
{
    public int Id { get; set; }

    public string BusinessTypeName { get; set; }

    public string Description { get; set; }

    public DateTime DateCreated { get; set; }

    public int? Status { get; set; }

    public string BusinessTypeId { get; set; }

    public int? IsVip { get; set; }

    public string ImgUrl { get; set; }

    public string PromoText { get; set; }
}