// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblBusinessLocationModel
{
    public int Id { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public DateTime DateCreated { get; set; }

    public int? Active { get; set; }

    public string BusinessLocId { get; set; }
}