// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblCorporatePrivilegeModel
{
    public int Id { get; set; }

    public int? CorporateId { get; set; }

    public DateTime? DateIssued { get; set; }

    public DateTime? ExpiryDate { get; set; }
}