// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblCorporatePrivilegeTierModel
{
    public int Id { get; set; }

    public int? PrivilegeId { get; set; }

    public int? CorporateId { get; set; }

    public string Count { get; set; }

    public string VipCount { get; set; }

    public int? IsVip { get; set; }
}