// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblCorporatePrivilegesModel
{
    public int Id { get; set; }

    public int? CorporateId { get; set; }

    public int? MembershipId { get; set; }

    public DateTime? DateIssued { get; set; }

    public DateTime? DateExpired { get; set; }

    public int? Count { get; set; }

    public int? Size { get; set; }

    public string Description { get; set; }

    public DateTime? DateCreated { get; set; }

    public int? Status { get; set; }
}