// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblNotificationModel
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public string Details { get; set; }

    public int? IsRead { get; set; }

    public DateTime DateCreated { get; set; }

    public string Module { get; set; }

    public string ItemId { get; set; }

    public int? EmailStatus { get; set; }
}