// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblOfferingModel
{
    public int Id { get; set; }

    public int? VendorId { get; set; }

    public int? MembershipId { get; set; }

    public int? BusinessTypeId { get; set; }

    public string OfferingName { get; set; }

    public string OfferingId { get; set; }

    public string PromoDesc { get; set; }

    public string PromoReleaseText { get; set; }

    public DateTime DateCreated { get; set; }

    public string ImgUrl { get; set; }

    public int? StatusId { get; set; }

    public int? PrivilegeId { get; set; }

    public string Url { get; set; }

    public string OfferDays { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string FromTime { get; set; }

    public string ToTime { get; set; }
}