// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblOfferingsModel
{
    public int Id { get; set; }

    public int? VendorId { get; set; }

    public string OfferingDesc { get; set; }

    public string PromoDesc { get; set; }

    public DateTime? Expiry { get; set; }

    public int? MembershipId { get; set; }

    public int? BusinessTypeId { get; set; }

    public string PromoReleaseText { get; set; }

    public DateTime? DateCreated { get; set; }

    public int? PrivilegeId { get; set; }

    public string Url { get; set; }

    public string OfferDays { get; set; }

    public DateTime? StartDatetime { get; set; }

    public DateTime? EndDatetime { get; set; }
}