// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Models;

public partial class TblVendorModel
{
    public int Id { get; set; }

    public string VendorName { get; set; }

    public int? BusinessTypeId { get; set; }

    public string Description { get; set; }

    public string Services { get; set; }

    public string WebsiteUrl { get; set; }

    public string FeatureImg { get; set; }

    public string Gallery { get; set; }

    public string Cno { get; set; }

    public string Email { get; set; }

    public string VideoUrl { get; set; }

    public string VrUrl { get; set; }

    public string VendorId { get; set; }

    public string BusinessLocationId { get; set; }

    public DateTime DateCreated { get; set; }

    public int? Status { get; set; }

    public string FileUrl { get; set; }

    public string Map { get; set; }

    public string VendorLogo { get; set; }

    public string Address { get; set; }
}