// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace CMS.Models
{
    public partial class UsersModel
    {
        public int Id { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string Fullname { get; set; }

        public string Fname { get; set; }

        public string Lname { get; set; }

        public string Mname { get; set; }

        public string Email { get; set; }

        public string Gender { get; set; }

        public string EmployeeId { get; set; }

        public int? CorporateId { get; set; }

        public int? PositionId { get; set; }

        public string Jwtoken { get; set; }

        public string FilePath { get; set; }

        public int? Type { get; set; }

        public int? Active { get; set; }

        public DateTime DateCreated { get; set; }

        public string Cno { get; set; }

        public int? IsVip { get; set; }

        public string Address { get; set; }

        public string Otp { get; set; }

        public int? AllowEmailNotif { get; set; }
    }
}